package com.janne6565.haulingcompanionapi.services.optimizer;

import java.util.Map;

public final class ShipRegistry {

    public static final Map<String, Integer> SHIPS = Map.ofEntries(
            Map.entry("AVENGER_TITAN",           8),
            Map.entry("HAMMERHEAD",              64),
            Map.entry("IDRIS_M",                 1326),
            Map.entry("IDRIS_P",                 1374),
            Map.entry("RECLAIMER",               420),
            Map.entry("REDEEMER",                2),
            Map.entry("RETALIATOR",              74),
            Map.entry("TIBURON",                 64),
            Map.entry("ASGARD",                  180),
            Map.entry("C8_PISCES",               4),
            Map.entry("C8X_PISCES",              4),
            Map.entry("CARRACK",                 456),
            Map.entry("F7C_HORNET_MK_I",         2),
            Map.entry("F7C_HORNET_MK_II",        2),
            Map.entry("LIBERATOR_CONCEPT",       400),
            Map.entry("PALADIN",                 4),
            Map.entry("VALKYRIE",                90),
            Map.entry("CSV_SM",                  4),
            Map.entry("MOLE",                    32),
            Map.entry("MOTH",                    224),
            Map.entry("MPUV_C",                  2),
            Map.entry("MPUV_T",                  16),
            Map.entry("RAFT",                    192),
            Map.entry("SRV",                     12),
            Map.entry("MERCHANTMAN_CONCEPT",     2880),
            Map.entry("MUSTANG_ALPHA",           4),
            Map.entry("NOMAD",                   24),
            Map.entry("PIONEER_CONCEPT",         1000),
            Map.entry("A2_HERCULES",             216),
            Map.entry("C1_SPIRIT",               64),
            Map.entry("C2_HERCULES",             696),
            Map.entry("INTREPID",                8),
            Map.entry("M2_HERCULES",             522),
            Map.entry("MERCURY_STAR_RUNNER",     114),
            Map.entry("CATERPILLAR",             576),
            Map.entry("CLIPPER",                 12),
            Map.entry("CORSAIR",                 72),
            Map.entry("CUTLASS_BLACK",           46),
            Map.entry("CUTLASS_BLUE",            12),
            Map.entry("CUTLASS_RED",             12),
            Map.entry("CUTTER",                  4),
            Map.entry("CUTTER_RAMBLER",          2),
            Map.entry("CUTTER_SCOUT",            2),
            Map.entry("GOLEM_OX",                64),
            Map.entry("IRONCLAD",                2200),
            Map.entry("IRONCLAD_ASSAULT",        1440),
            Map.entry("MULE",                    1),
            Map.entry("VULTURE",                 13),
            Map.entry("PROWLER_UTILITY",         32),
            Map.entry("RAILEN_CONCEPT",          640),
            Map.entry("SYULEN",                  6),
            Map.entry("SHIV",                    32),
            Map.entry("FORTUNE",                 16),
            Map.entry("FREELANCER",              66),
            Map.entry("FREELANCER_DUR",          36),
            Map.entry("FREELANCER_MAX",          120),
            Map.entry("FREELANCER_MIS",          36),
            Map.entry("HULL_A",                  64),
            Map.entry("HULL_B",                  512),
            Map.entry("HULL_C",                  4608),
            Map.entry("HULL_D_CONCEPT",          6912),
            Map.entry("HULL_E_CONCEPT",          12288),
            Map.entry("RELIANT_KORE",            6),
            Map.entry("RELIANT_TANA",            1),
            Map.entry("STARFARER",               291),
            Map.entry("STARFARER_GEMINI",        291),
            Map.entry("STARLANCER_MAX",          224),
            Map.entry("STARLANCER_TAC",          96),
            Map.entry("100I",                    2),
            Map.entry("125A",                    2),
            Map.entry("135C",                    6),
            Map.entry("300I",                    8),
            Map.entry("315P",                    12),
            Map.entry("325A",                    4),
            Map.entry("350R",                    4),
            Map.entry("400I",                    42),
            Map.entry("600I_EXPLORER",           44),
            Map.entry("600I_TOURING",            20),
            Map.entry("890_JUMP",                388),
            Map.entry("M80",                     2),
            Map.entry("APOLLO_MEDIVAC",          32),
            Map.entry("APOLLO_TRIAGE",           32),
            Map.entry("ARRASTRA_CONCEPT",        576),
            Map.entry("AURORA_MK_II",            2),
            Map.entry("AURORA_MK_II_CARGO",      8),
            Map.entry("AURORA_CL_MK_I",          6),
            Map.entry("AURORA_ES_MK_I",          3),
            Map.entry("AURORA_LN_MK_I",          3),
            Map.entry("AURORA_LX_MK_I",          3),
            Map.entry("AURORA_MR_MK_I",          3),
            Map.entry("CONSTELLATION_ANDROMEDA", 96),
            Map.entry("CONSTELLATION_AQUILA",    96),
            Map.entry("CONSTELLATION_PHOENIX",   80),
            Map.entry("CONSTELLATION_TAURUS",    174),
            Map.entry("GALAXY_BASE_CONCEPT",     64),
            Map.entry("GALAXY_CARGO_CONCEPT",    576),
            Map.entry("HERMES",                  288),
            Map.entry("PERSEUS",                 96),
            Map.entry("POLARIS",                 576),
            Map.entry("SALVATION",               6),
            Map.entry("ZEUS_MK_II_CL",           128),
            Map.entry("ZEUS_MK_II_ES",           32),
            Map.entry("ZEUS_MK_II_MR_CONCEPT",   16),
            Map.entry("CYCLONE",                 1)
    );

    private ShipRegistry() {}

    public static int capacityFor(String ship) {
        return SHIPS.getOrDefault(ship, Integer.MAX_VALUE);
    }
}
